### ISSUE TITLE
Ansible Azure library version issues

### ISSUE THREAD

**Issue by mo-moneyy** [ansible/ansible_collections_azure#130]
##### SUMMARY

As requested, I have moved this to here from [here](https://github.com/ansible/ansible/issues/69672).

I have an app that I running in a Docker container to create Azure resources utilizing Ansible and Python. I have installed the necessary arm modules with `pip install ansible[azure]` to enable Ansible to work with Azure. For my Python script i am using the current azure-storage-blob, azure-mgmt-resource, and azure-common libraries. Everything with my app works and does what it needs to do locally.

The required Ansible libraries for Azure are listed [here](https://github.com/ansible/ansible/blob/stable-2.8/packaging/requirements/requirements-azure.txt) These versions are extremely outdated. The problem I am facing is on the build of the Docker image, the required libraries for Ansible are being installed (using `pip install ansible[azure]`) and then when I install the necessary libraries for the Python script (azure-storage-blob, azure-mgmt-resource, and azure-common) pip is blowing away the old versions needed for Ansible. Those three that I need for Python are in the list of required Ansible libraries hence why they are being blown away. It's a lose lose situation. If I want the python script to work, I need relatively current Azure libraries. If I want my playbooks to work, I need to use the very dated libraries. Is there anything I can do to get these libraries from uninstalling each other? I am not too sure if there is anything that can be done, but I think its definitely something that should be brought up.

I believe the azure-storage-blob module is what is breaking my playbook. In the list of libraries needed for Ansible, it requires the module azure-storage 0.35.1. This has been deprecated for a long time now and was replaced by azure-storage-blob. azure-storage-blob is on version 12.0.

Examples of the uninstalls during the Docker run:

Installing collected packages: azure-mgmt-resource
Attempting uninstall: azure-mgmt-resource
Found existing installation: azure-mgmt-resource 2.1.0
Uninstalling azure-mgmt-resource-2.1.0:
Successfully uninstalled azure-mgmt-resource-2.1.0
Successfully installed azure-mgmt-resource-9.0.0

2.1 is what's needed and being used still? They are up to 9.0.

Installing collected packages: azure-core, msrest, azure-storage-blob
Attempting uninstall: msrest
Found existing installation: msrest 0.6.1
Uninstalling msrest-0.6.1:
Successfully uninstalled msrest-0.6.1
Successfully installed azure-core-1.5.0 azure-storage-blob-12.3.0 msrest-0.6.14

`pip3 freeze | grep azure` results:

These are the versions that I ran the playbook with below.

azure-cli-core==2.0.35
azure-cli-nspkg==3.0.2
azure-common==1.1.25
azure-core==1.5.0
azure-graphrbac==0.40.0
azure-keyvault==1.0.0a1
azure-mgmt-authorization==0.51.1
azure-mgmt-automation==0.1.1
azure-mgmt-batch==5.0.1
azure-mgmt-cdn==3.0.0
azure-mgmt-compute==4.4.0
azure-mgmt-containerinstance==1.4.0
azure-mgmt-containerregistry==2.0.0
azure-mgmt-containerservice==4.4.0
azure-mgmt-cosmosdb==0.5.2
azure-mgmt-devtestlabs==3.0.0
azure-mgmt-dns==2.1.0
azure-mgmt-hdinsight==0.1.0
azure-mgmt-iothub==0.7.0
azure-mgmt-keyvault==1.1.0
azure-mgmt-loganalytics==0.2.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-monitor==0.5.2
azure-mgmt-network==2.3.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==1.4.1
azure-mgmt-redis==5.0.0
azure-mgmt-resource==9.0.0
azure-mgmt-servicebus==0.5.3
azure-mgmt-sql==0.10.0
azure-mgmt-storage==3.1.0
azure-mgmt-trafficmanager==0.50.0
azure-mgmt-web==0.41.0
azure-nspkg==2.0.0
azure-storage==0.35.1
azure-storage-blob==12.3.0
msrestazure==0.5.0
##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible 2.9.9
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/var/www/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

This is just a snippet of the playbook I am using but it is erroring out because the azure-storage-blob library and azure-storage library cannot coexist. I know this because running the playbook without the azure-storage-library installed, it works.

```yaml
- name: Download vars
      azure_rm_storageblob:
        resource_group: <resource group>
        storage_account_name: <storage account name>
        container: <container>
        blob: <blob>
        dest: /path/to/ex.yml
```

##### ACTUAL RESULTS

```paste below
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: cannot import name 'PageBlobService'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on c3950e31c1f7's Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library
is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"}
```

**Comment by mo-moneyy** [comment]
The os is Ubuntu 18.04

**Comment by mo-moneyy** [comment]
Any update to this?

**Comment by UnwashedMeme** [comment]
#139  is related; updating to use newer azure libraries would resolve that too.

**Comment by Fred-sun** [comment]
@tigerkeeper5 Thank you for submitting this question, but I have never encountered the problem you encountered. Generally speaking, you only need to install ansible, azure.azcollection and related dependencies. You can uninstall conflicting packages and ansible, and try the following steps? Thank you!
```e.g.

1.  sudo pip3 install ansible

2.  ansible-galaxy collection install azure.azcollection --force

3.  sudo pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt

**Comment by mo-moneyy** [comment]
@Fred-sun I appreciate the response, but that does not solve the problem at hand. The problem is that I need to leverage the azure.storage.blob library. The deprecated version of that library is azure-storage 0.35.1 which is what you guys use for the Azure Ansible modules. My Python script needs the azure.storage.blob and the ansible playbook needs azure-storage 0.35.1. These two libraries **cannot** coexist together. 

If you run `sudo pip3 install ansible, ansible-galaxy collection install azure.azcollection --force`,  `sudo pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt`, that gets you all the necessary tools for Ansible Azure and my playbook works. But as soon as I install the python sdk azure.storage.blob, that becomes the primary storage option that Ansible looks at. It will no longer use azure-storage 0.35.1 resulting in the playbook erroring out. I.e:

`"msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"`

As you can see the [azure-storage library](https://pypi.org/project/azure-storage/) is deprecated and they recommend to use the other collections. This is a bug in your guys' code. If you upgrade your libraries to use the current sdk's, this would solve the issue. 

Steps to recreate issue:

1. `pip3 install ansible[azure]` or the ansible-galaxy install you sent.
2. Run a playbook with any type of azure resource creation ( I am using azure_rm_resourcegroup, azure_rm_virtualnetwork, azure_rm_subnet, azure_rm_roleassignment, and azure_rm_storageblob) just to have something that works
3. Next, do a `pip3 install azure-storage-blob==12.3.0`
4. Finally, run the playbook that you did in step 2.

**Comment by Fred-sun** [comment]
@UnwashedMeme After you install it, can you reinstall azure-cli(the reason for the error) and try again? Thank you！
```e.g.
sudo pip3 install azure-cli -I
```
```e.g.
"msg": "Failed to import the required Python library (ansible[azure] (azure >= 2.0.0)) on Python /usr/bin/python3. Please read module documentation and install in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter"

**Comment by Fred-sun** [comment]
@UnwashedMeme Any feedback for this?

**Comment by UnwashedMeme** [comment]
@Fred-sun I haven't really looked at this; @tigerkeeper5 is the one having trouble.   From reading this post I expect he still has the same problem because the [requirements-azure.txt](https://github.com/ansible-collections/azure/blob/8248c87/requirements-azure.txt) file (the current HEAD of dev) still references `azure-storage==0.35.1` [which is deprecated](https://pypi.org/project/azure-storage/), as @tigerkeeper5  pointed out above.

I notice that this is part of the broader issue this collection has with using out of date azure libraries.  That's why I asked [if there was any plan to systematically upgrade](https://github.com/ansible-collections/azure/pull/246#issuecomment-688912055).

**Comment by Fred-sun** [comment]
Thanks @UnwashedMeme.

**Comment by hectoralicea** [comment]
I'm having the exact same issue.  The requirement for azure-cli, even when deployed in a manner consistent with how Microsoft official Docker `azure-cli` is installed in their Dockerfile, conflicts with the requirement file for `ansible[azure]`

If someone can provide which version of ansible[azure] is compatible with a certain version of azure cli, I'm able to control the version of either when creating my docker image.  Right now I'm using `ansible==2.9.11` `ansible[azure]==2.9.11`  and the azure cli `2.9.1` based on the tag   `azure-cli-2.9.1`

**Comment by joaocc** [comment]
Hi. Any updates on this topic? I am also facing similar difficulties when trying to use either ansible[azure] 2.9, and ansible-base 2.10. Thanks

**Comment by hectoralicea** [comment]
Here's a docker file I use to  builds the perfect ansible / azure cli / kubernetes container I use to run my azure / kubernetes ansible playbooks. If anyone knows of a simpler approach to this please advise.
[Dockerfile.zip](https://github.com/ansible-collections/azure/files/5712161/Dockerfile.zip)

**Comment by Xaeco** [comment]
I can't use `azure_rm_storageblob` because it wants ansible[azure] which is deprecated and causes all sorts of module version conflicts if I try to install all dependencies. 

If anyone is successfully using `azure_rm_storageblob` I'd like to know how.

**Comment by jfreeland** [comment]
does clicking on the thumbs up here on the initial comment have any impact to prioritization?  it's pretty surprising how far behind this is re: azure python sdk.  i also had to do some reworking of other dependencies to support how far behind this is. 😱    is there someone from azure that maintains this stuff?  if so, this makes it harder for me to give you money.  please fix.

**Comment by Fred-sun** [comment]
@jfreeland We are preparing to update all depend packages! once upgrade, I will add comment in here! Thank you very much!

**Comment by tadrian88** [comment]
any update @Fred-sun ?

**Comment by Fred-sun** [comment]
@tadrian88 Recently, because I am busy with other things, the update has not been completed. Thank you very much!

**Comment by l3ender** [comment]
@Fred-sun Is there a timeline for the dependency package update? Is there anything I can do to assist the effort? Thank you!

**Comment by Fred-sun** [comment]
> @Fred-sun Is there a timeline for the dependency package update? Is there anything I can do to assist the effort? Thank you!

This is in the plan temporarily, the specific completion time has not been determined. Thank you very much!

**Comment by l3ender** [comment]
I have started work on updating the azure-storage dependency in https://github.com/ansible-collections/azure/pull/833 and hope to complete this week!

**Comment by jdelvecchio** [comment]
Hi @l3ender - any update on this ? thanks a lot!

**Comment by l3ender** [comment]
@jdelvecchio Yes, https://github.com/ansible-collections/azure/pull/833 is ready and waiting for review from @Fred-sun! Thank you!

**Comment by l3ender** [comment]
This issue has been resolved with https://github.com/ansible-collections/azure/pull/833. It is merged to dev and should be included in the next release (>v1.13.0).

Please note that if you are updating an existing python environment with previously-installed dependencies, you will need to explicitly uninstall the old storage dependency (do this before installing the updated from requirements-azure.txt):
```bash
pip uninstall azure-storage
```

Thanks!

**Comment by jdelvecchio** [comment]
To me, this is not resolved yet. 
Example : 

```
ansible-galaxy collection install azure.azcollection
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Downloading https://galaxy.ansible.com/download/azure-azcollection-1.13.0.tar.gz to /root/.ansible/tmp/ansible-local-24ek_u6fyo/tmp9jqu038i/azure-azcollection-1.13.0-cg_px_p7
Installing 'azure.azcollection:1.13.0' to '/root/.ansible/collections/ansible_collections/azure/azcollection'
azure.azcollection:1.13.0 was installed successfully
$ pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
Requirement already satisfied: packaging in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 1)) (21.3)
Requirement already satisfied: requests[security] in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 2)) (2.27.1)
Requirement already satisfied: xmltodict in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 3)) (0.12.0)
Collecting azure-cli-core==2.34.0
  Downloading azure_cli_core-2.34.0-py3-none-any.whl (179 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 179.4/179.4 KB 4.0 MB/s eta 0:00:00
Collecting azure-common==1.1.11
  Downloading azure_common-1.1.11-py2.py3-none-any.whl (9.7 kB)
Collecting azure-identity==1.7.0
  Downloading azure_identity-1.7.0-py2.py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 KB 6.1 MB/s eta 0:00:00
Collecting azure-mgmt-apimanagement==0.2.0
  Downloading azure_mgmt_apimanagement-0.2.0-py2.py3-none-any.whl (275 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 275.3/275.3 KB 13.9 MB/s eta 0:00:00
Collecting azure-mgmt-authorization==0.51.1
  Downloading azure_mgmt_authorization-0.51.1-py2.py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.4/111.4 KB 7.0 MB/s eta 0:00:00
Collecting azure-mgmt-batch==5.0.1
  Downloading azure_mgmt_batch-5.0.1-py2.py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.1/87.1 KB 7.9 MB/s eta 0:00:00
Collecting azure-mgmt-cdn==3.0.0
  Downloading azure_mgmt_cdn-3.0.0-py2.py3-none-any.whl (108 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 108.9/108.9 KB 8.0 MB/s eta 0:00:00
Collecting azure-mgmt-compute==26.1.0
  Downloading azure_mgmt_compute-26.1.0-py3-none-any.whl (4.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.8/4.8 MB 30.7 MB/s eta 0:00:00
Collecting azure-mgmt-containerinstance==1.4.0
  Downloading azure_mgmt_containerinstance-1.4.0-py2.py3-none-any.whl (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.5/87.5 KB 9.3 MB/s eta 0:00:00
Collecting azure-mgmt-containerregistry==2.0.0
  Downloading azure_mgmt_containerregistry-2.0.0-py2.py3-none-any.whl (274 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 274.6/274.6 KB 15.5 MB/s eta 0:00:00
Collecting azure-mgmt-containerservice==9.1.0
  Downloading azure_mgmt_containerservice-9.1.0-py2.py3-none-any.whl (545 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 546.0/546.0 KB 22.9 MB/s eta 0:00:00
Requirement already satisfied: azure-mgmt-datalake-store==0.5.0 in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 15)) (0.5.0)
Collecting azure-mgmt-datafactory==2.0.0
  Downloading azure_mgmt_datafactory-2.0.0-py2.py3-none-any.whl (514 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 514.1/514.1 KB 23.0 MB/s eta 0:00:00
Collecting azure-mgmt-dns==2.1.0
  Downloading azure_mgmt_dns-2.1.0-py2.py3-none-any.whl (134 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 KB 12.2 MB/s eta 0:00:00
Collecting azure-mgmt-keyvault==1.1.0
  Downloading azure_mgmt_keyvault-1.1.0-py2.py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.0/112.0 KB 11.2 MB/s eta 0:00:00
Collecting azure-mgmt-marketplaceordering==0.1.0
  Downloading azure_mgmt_marketplaceordering-0.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: azure-mgmt-monitor==3.0.0 in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 20)) (3.0.0)
Requirement already satisfied: azure-mgmt-managedservices==1.0.0 in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 21)) (1.0.0)
Collecting azure-mgmt-managementgroups==0.2.0
  Downloading azure_mgmt_managementgroups-0.2.0-py2.py3-none-any.whl (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.5/59.5 KB 5.4 MB/s eta 0:00:00
Collecting azure-mgmt-network==19.1.0
  Downloading azure_mgmt_network-19.1.0-py2.py3-none-any.whl (22.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.0/22.0 MB 22.4 MB/s eta 0:00:00
Collecting azure-mgmt-nspkg==2.0.0
  Downloading azure_mgmt_nspkg-2.0.0-py2.py3-none-any.whl (2.8 kB)
Collecting azure-mgmt-privatedns==0.1.0
  Downloading azure_mgmt_privatedns-0.1.0-py2.py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 KB 3.6 MB/s eta 0:00:00
Collecting azure-mgmt-redis==13.0.0
  Downloading azure_mgmt_redis-13.0.0-py2.py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.9/75.9 KB 6.4 MB/s eta 0:00:00
Collecting azure-mgmt-resource==10.2.0
  Downloading azure_mgmt_resource-10.2.0-py2.py3-none-any.whl (968 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 968.5/968.5 KB 24.1 MB/s eta 0:00:00
Collecting azure-mgmt-rdbms==1.9.0
  Downloading azure_mgmt_rdbms-1.9.0-py2.py3-none-any.whl (259 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.5/259.5 KB 17.6 MB/s eta 0:00:00
Collecting azure-mgmt-search==3.0.0
  Downloading azure_mgmt_search-3.0.0-py2.py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.1/43.1 KB 4.6 MB/s eta 0:00:00
Collecting azure-mgmt-servicebus==0.5.3
  Downloading azure_mgmt_servicebus-0.5.3-py2.py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.0/112.0 KB 10.1 MB/s eta 0:00:00
Requirement already satisfied: azure-mgmt-sql==3.0.1 in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 31)) (3.0.1)
Collecting azure-mgmt-storage==19.0.0
  Downloading azure_mgmt_storage-19.0.0-py2.py3-none-any.whl (1.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 29.5 MB/s eta 0:00:00
Collecting azure-mgmt-trafficmanager==0.50.0
  Downloading azure_mgmt_trafficmanager-0.50.0-py2.py3-none-any.whl (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 KB 5.8 MB/s eta 0:00:00
Collecting azure-mgmt-web==0.41.0
  Downloading azure_mgmt_web-0.41.0-py2.py3-none-any.whl (645 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 645.8/645.8 KB 25.3 MB/s eta 0:00:00
Collecting azure-nspkg==2.0.0
  Downloading azure_nspkg-2.0.0-py2.py3-none-any.whl (2.6 kB)
Collecting azure-storage==0.35.1
  Downloading azure_storage-0.35.1-py2.py3-none-any.whl (190 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 190.2/190.2 KB 16.8 MB/s eta 0:00:00
Requirement already satisfied: msrest==0.6.21 in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 37)) (0.6.21)
Requirement already satisfied: msrestazure==0.6.4 in /usr/lib/python3.9/site-packages (from -r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 38)) (0.6.4)
Collecting azure-keyvault==1.0.0a1
  Downloading azure_keyvault-1.0.0a1-py2.py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.9/109.9 KB 9.8 MB/s eta 0:00:00
Collecting azure-graphrbac==0.61.1
  Downloading azure_graphrbac-0.61.1-py2.py3-none-any.whl (141 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.4/141.4 KB 12.3 MB/s eta 0:00:00
Collecting azure-mgmt-cosmosdb==0.15.0
  Downloading azure_mgmt_cosmosdb-0.15.0-py2.py3-none-any.whl (111 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 111.2/111.2 KB 11.6 MB/s eta 0:00:00
Collecting azure-mgmt-hdinsight==0.1.0
  Downloading azure_mgmt_hdinsight-0.1.0-py2.py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.9/117.9 KB 3.1 MB/s eta 0:00:00
Collecting azure-mgmt-devtestlabs==3.0.0
  Downloading azure_mgmt_devtestlabs-3.0.0-py2.py3-none-any.whl (381 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.5/381.5 KB 17.6 MB/s eta 0:00:00
Collecting azure-mgmt-loganalytics==1.0.0
  Downloading azure_mgmt_loganalytics-1.0.0-py2.py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 KB 8.2 MB/s eta 0:00:00
Collecting azure-mgmt-automation==1.0.0
  Downloading azure_mgmt_automation-1.0.0-py2.py3-none-any.whl (287 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.9/287.9 KB 16.7 MB/s eta 0:00:00
Collecting azure-mgmt-iothub==0.7.0
  Downloading azure_mgmt_iothub-0.7.0-py2.py3-none-any.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.7/131.7 KB 8.4 MB/s eta 0:00:00
Collecting azure-mgmt-recoveryservices==0.4.0
  Downloading azure_mgmt_recoveryservices-0.4.0-py2.py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.7/77.7 KB 7.2 MB/s eta 0:00:00
Collecting azure-mgmt-recoveryservicesbackup==0.6.0
  Downloading azure_mgmt_recoveryservicesbackup-0.6.0-py2.py3-none-any.whl (194 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.6/194.6 KB 13.6 MB/s eta 0:00:00
Collecting azure-mgmt-notificationhubs==2.0.0
  Downloading azure_mgmt_notificationhubs-2.0.0-py2.py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.7/71.7 KB 7.2 MB/s eta 0:00:00
Collecting azure-mgmt-eventhub==2.0.0
  Downloading azure_mgmt_eventhub-2.0.0-py2.py3-none-any.whl ([67](https://gitlab.com/fnacdarty/fdps/ops/teams/kyndrylprojetdebord/infra/azr-fcom-nav-debord-app-image/-/jobs/2599457832#L67) kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.4/67.4 KB 5.5 MB/s eta 0:00:00
Requirement already satisfied: psutil~=5.9 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (5.9.0)
Requirement already satisfied: jmespath in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.0.0)
Requirement already satisfied: argcomplete~=1.8 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.12.3)
Requirement already satisfied: msal-extensions<0.4,>=0.3.1 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (0.3.1)
Requirement already satisfied: cryptography in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (36.0.2)
Requirement already satisfied: pyopenssl>=17.1.0 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (22.0.0)
Requirement already satisfied: PyJWT>=2.1.0 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (2.3.0)
Requirement already satisfied: azure-mgmt-core<2,>=1.2.0 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.3.0)
Requirement already satisfied: knack~=0.9.0 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (0.9.0)
Requirement already satisfied: azure-cli-telemetry==1.0.6.* in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.0.6)
Requirement already satisfied: humanfriendly~=10.0 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (10.0)
Requirement already satisfied: paramiko<3.0.0,>=2.0.8 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (2.10.3)
Requirement already satisfied: pkginfo>=1.5.0.1 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.8.2)
Requirement already satisfied: msal<2.0.0,>=1.16.0 in /usr/lib/python3.9/site-packages (from azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.17.0)
Requirement already satisfied: six>=1.12.0 in /usr/lib/python3.9/site-packages (from azure-identity==1.7.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 6)) (1.16.0)
Requirement already satisfied: azure-core<2.0.0,>=1.11.0 in /usr/lib/python3.9/site-packages (from azure-identity==1.7.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 6)) (1.23.0)
Requirement already satisfied: azure-mgmt-datalake-nspkg>=2.0.0 in /usr/lib/python3.9/site-packages (from azure-mgmt-datalake-store==0.5.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 15)) (3.0.1)
Requirement already satisfied: python-dateutil in /usr/lib/python3.9/site-packages (from azure-storage==0.35.1->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 36)) (2.8.2)
Requirement already satisfied: requests-oauthlib>=0.5.0 in /usr/lib/python3.9/site-packages (from msrest==0.6.21->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 37)) (1.3.1)
Requirement already satisfied: isodate>=0.6.0 in /usr/lib/python3.9/site-packages (from msrest==0.6.21->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 37)) (0.6.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3.9/site-packages (from msrest==0.6.21->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 37)) (2021.10.8)
Requirement already satisfied: adal<2.0.0,>=0.6.0 in /usr/lib/python3.9/site-packages (from msrestazure==0.6.4->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 38)) (1.2.7)
Requirement already satisfied: portalocker~=1.2 in /usr/lib/python3.9/site-packages (from azure-cli-telemetry==1.0.6.*->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.7.1)
Requirement already satisfied: applicationinsights<0.12,>=0.11.1 in /usr/lib/python3.9/site-packages (from azure-cli-telemetry==1.0.6.*->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (0.11.10)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3.9/site-packages (from packaging->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 1)) (3.0.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/lib/python3.9/site-packages (from requests[security]->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 2)) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3.9/site-packages (from requests[security]->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 2)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests[security]->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 2)) (1.26.9)
Requirement already satisfied: typing-extensions>=4.0.1 in /usr/lib/python3.9/site-packages (from azure-core<2.0.0,>=1.11.0->azure-identity==1.7.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 6)) (4.1.1)
Collecting azure-mgmt-datalake-nspkg>=2.0.0
  Downloading azure_mgmt_datalake_nspkg-2.0.0-py2.py3-none-any.whl (3.0 kB)
Requirement already satisfied: cffi>=1.12 in /usr/lib/python3.9/site-packages (from cryptography->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.15.0)
Requirement already satisfied: pyyaml in /usr/lib/python3.9/site-packages (from knack~=0.9.0->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (6.0)
Requirement already satisfied: tabulate in /usr/lib/python3.9/site-packages (from knack~=0.9.0->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (0.8.9)
Requirement already satisfied: pygments in /usr/lib/python3.9/site-packages (from knack~=0.9.0->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (2.11.2)
Requirement already satisfied: pynacl>=1.0.1 in /usr/lib/python3.9/site-packages (from paramiko<3.0.0,>=2.0.8->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (1.4.0)
Requirement already satisfied: bcrypt>=3.1.3 in /usr/lib/python3.9/site-packages (from paramiko<3.0.0,>=2.0.8->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (3.2.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/lib/python3.9/site-packages (from requests-oauthlib>=0.5.0->msrest==0.6.21->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 37)) (3.2.0)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/lib/python3.9/site-packages (from requests[security]->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 2)) (1.7.1)
Requirement already satisfied: pycparser in /usr/lib/python3.9/site-packages (from cffi>=1.12->cryptography->azure-cli-core==2.34.0->-r /root/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt (line 4)) (2.21)
Installing collected packages: azure-nspkg, azure-mgmt-nspkg, azure-common, azure-mgmt-datalake-nspkg, azure-storage, azure-mgmt-storage, azure-mgmt-redis, azure-mgmt-network, azure-mgmt-datafactory, azure-mgmt-compute, azure-mgmt-automation, azure-mgmt-web, azure-mgmt-trafficmanager, azure-mgmt-servicebus, azure-mgmt-search, azure-mgmt-resource, azure-mgmt-recoveryservicesbackup, azure-mgmt-recoveryservices, azure-mgmt-rdbms, azure-mgmt-privatedns, azure-mgmt-notificationhubs, azure-mgmt-marketplaceordering, azure-mgmt-managementgroups, azure-mgmt-loganalytics, azure-mgmt-keyvault, azure-mgmt-iothub, azure-mgmt-hdinsight, azure-mgmt-eventhub, azure-mgmt-dns, azure-mgmt-devtestlabs, azure-mgmt-cosmosdb, azure-mgmt-containerservice, azure-mgmt-containerregistry, azure-mgmt-containerinstance, azure-mgmt-cdn, azure-mgmt-batch, azure-mgmt-authorization, azure-mgmt-apimanagement, azure-keyvault, azure-graphrbac, azure-identity, azure-cli-core
  Attempting uninstall: azure-nspkg
    Found existing installation: azure-nspkg 3.0.2
    Uninstalling azure-nspkg-3.0.2:
      Successfully uninstalled azure-nspkg-3.0.2
  Attempting uninstall: azure-mgmt-nspkg
    Found existing installation: azure-mgmt-nspkg 3.0.2
    Uninstalling azure-mgmt-nspkg-3.0.2:
      Successfully uninstalled azure-mgmt-nspkg-3.0.2
  Attempting uninstall: azure-common
    Found existing installation: azure-common 1.1.28
    Uninstalling azure-common-1.1.28:
      Successfully uninstalled azure-common-1.1.28
  Attempting uninstall: azure-mgmt-datalake-nspkg
    Found existing installation: azure-mgmt-datalake-nspkg 3.0.1
    Uninstalling azure-mgmt-datalake-nspkg-3.0.1:
      Successfully uninstalled azure-mgmt-datalake-nspkg-3.0.1
  Attempting uninstall: azure-mgmt-storage
    Found existing installation: azure-mgmt-storage 19.1.0
    Uninstalling azure-mgmt-storage-19.1.0:
      Successfully uninstalled azure-mgmt-storage-19.1.0
  Attempting uninstall: azure-mgmt-redis
    Found existing installation: azure-mgmt-redis 13.1.0
    Uninstalling azure-mgmt-redis-13.1.0:
      Successfully uninstalled azure-mgmt-redis-13.1.0
  Attempting uninstall: azure-mgmt-network
    Found existing installation: azure-mgmt-network 19.3.0
    Uninstalling azure-mgmt-network-19.3.0:
      Successfully uninstalled azure-mgmt-network-19.3.0
  Attempting uninstall: azure-mgmt-compute
    Found existing installation: azure-mgmt-compute 25.0.0
    Uninstalling azure-mgmt-compute-25.0.0:
      Successfully uninstalled azure-mgmt-compute-25.0.0
  Attempting uninstall: azure-mgmt-web
    Found existing installation: azure-mgmt-web 6.1.0
    Uninstalling azure-mgmt-web-6.1.0:
      Successfully uninstalled azure-mgmt-web-6.1.0
  Attempting uninstall: azure-mgmt-trafficmanager
    Found existing installation: azure-mgmt-trafficmanager 1.0.0
    Uninstalling azure-mgmt-trafficmanager-1.0.0:
      Successfully uninstalled azure-mgmt-trafficmanager-1.0.0
  Attempting uninstall: azure-mgmt-servicebus
    Found existing installation: azure-mgmt-servicebus 7.1.0
    Uninstalling azure-mgmt-servicebus-7.1.0:
      Successfully uninstalled azure-mgmt-servicebus-7.1.0
  Attempting uninstall: azure-mgmt-search
    Found existing installation: azure-mgmt-search 8.0.0
    Uninstalling azure-mgmt-search-8.0.0:
      Successfully uninstalled azure-mgmt-search-8.0.0
  Attempting uninstall: azure-mgmt-resource
    Found existing installation: azure-mgmt-resource 20.0.0
    Uninstalling azure-mgmt-resource-20.0.0:
      Successfully uninstalled azure-mgmt-resource-20.0.0
  Attempting uninstall: azure-mgmt-recoveryservicesbackup
    Found existing installation: azure-mgmt-recoveryservicesbackup 4.0.0
    Uninstalling azure-mgmt-recoveryservicesbackup-4.0.0:
      Successfully uninstalled azure-mgmt-recoveryservicesbackup-4.0.0
  Attempting uninstall: azure-mgmt-recoveryservices
    Found existing installation: azure-mgmt-recoveryservices 2.0.0
    Uninstalling azure-mgmt-recoveryservices-2.0.0:
      Successfully uninstalled azure-mgmt-recoveryservices-2.0.0
  Attempting uninstall: azure-mgmt-rdbms
    Found existing installation: azure-mgmt-rdbms 10.0.0
    Uninstalling azure-mgmt-rdbms-10.0.0:
      Successfully uninstalled azure-mgmt-rdbms-10.0.0
  Attempting uninstall: azure-mgmt-privatedns
    Found existing installation: azure-mgmt-privatedns 1.0.0
    Uninstalling azure-mgmt-privatedns-1.0.0:
      Successfully uninstalled azure-mgmt-privatedns-1.0.0
  Attempting uninstall: azure-mgmt-marketplaceordering
    Found existing installation: azure-mgmt-marketplaceordering 1.1.0
    Uninstalling azure-mgmt-marketplaceordering-1.1.0:
      Successfully uninstalled azure-mgmt-marketplaceordering-1.1.0
  Attempting uninstall: azure-mgmt-managementgroups
    Found existing installation: azure-mgmt-managementgroups 1.0.0
    Uninstalling azure-mgmt-managementgroups-1.0.0:
      Successfully uninstalled azure-mgmt-managementgroups-1.0.0
  Attempting uninstall: azure-mgmt-loganalytics
    Found existing installation: azure-mgmt-loganalytics 13.0.0b2
    Uninstalling azure-mgmt-loganalytics-13.0.0b2:
      Successfully uninstalled azure-mgmt-loganalytics-13.0.0b2
  Attempting uninstall: azure-mgmt-keyvault
    Found existing installation: azure-mgmt-keyvault 9.3.0
    Uninstalling azure-mgmt-keyvault-9.3.0:
      Successfully uninstalled azure-mgmt-keyvault-9.3.0
  Attempting uninstall: azure-mgmt-iothub
    Found existing installation: azure-mgmt-iothub 2.2.0
    Uninstalling azure-mgmt-iothub-2.2.0:
      Successfully uninstalled azure-mgmt-iothub-2.2.0
  Attempting uninstall: azure-mgmt-hdinsight
    Found existing installation: azure-mgmt-hdinsight 9.0.0
    Uninstalling azure-mgmt-hdinsight-9.0.0:
      Successfully uninstalled azure-mgmt-hdinsight-9.0.0
  Attempting uninstall: azure-mgmt-eventhub
    Found existing installation: azure-mgmt-eventhub 9.1.0
    Uninstalling azure-mgmt-eventhub-9.1.0:
      Successfully uninstalled azure-mgmt-eventhub-9.1.0
  Attempting uninstall: azure-mgmt-dns
    Found existing installation: azure-mgmt-dns 8.0.0
    Uninstalling azure-mgmt-dns-8.0.0:
      Successfully uninstalled azure-mgmt-dns-8.0.0
  Attempting uninstall: azure-mgmt-devtestlabs
    Found existing installation: azure-mgmt-devtestlabs 4.0.0
    Uninstalling azure-mgmt-devtestlabs-4.0.0:
      Successfully uninstalled azure-mgmt-devtestlabs-4.0.0
  Attempting uninstall: azure-mgmt-cosmosdb
    Found existing installation: azure-mgmt-cosmosdb 7.0.0b3
    Uninstalling azure-mgmt-cosmosdb-7.0.0b3:
      Successfully uninstalled azure-mgmt-cosmosdb-7.0.0b3
  Attempting uninstall: azure-mgmt-containerservice
    Found existing installation: azure-mgmt-containerservice 17.0.0
    Uninstalling azure-mgmt-containerservice-17.0.0:
      Successfully uninstalled azure-mgmt-containerservice-17.0.0
  Attempting uninstall: azure-mgmt-containerregistry
    Found existing installation: azure-mgmt-containerregistry 8.2.0
    Uninstalling azure-mgmt-containerregistry-8.2.0:
      Successfully uninstalled azure-mgmt-containerregistry-8.2.0
  Attempting uninstall: azure-mgmt-containerinstance
    Found existing installation: azure-mgmt-containerinstance 9.1.0
    Uninstalling azure-mgmt-containerinstance-9.1.0:
      Successfully uninstalled azure-mgmt-containerinstance-9.1.0
  Attempting uninstall: azure-mgmt-cdn
    Found existing installation: azure-mgmt-cdn 11.0.0
    Uninstalling azure-mgmt-cdn-11.0.0:
      Successfully uninstalled azure-mgmt-cdn-11.0.0
  Attempting uninstall: azure-mgmt-batch
    Found existing installation: azure-mgmt-batch 16.0.0
    Uninstalling azure-mgmt-batch-16.0.0:
      Successfully uninstalled azure-mgmt-batch-16.0.0
  Attempting uninstall: azure-mgmt-authorization
    Found existing installation: azure-mgmt-authorization 0.61.0
    Uninstalling azure-mgmt-authorization-0.61.0:
      Successfully uninstalled azure-mgmt-authorization-0.61.0
  Attempting uninstall: azure-mgmt-apimanagement
    Found existing installation: azure-mgmt-apimanagement 3.0.0
    Uninstalling azure-mgmt-apimanagement-3.0.0:
      Successfully uninstalled azure-mgmt-apimanagement-3.0.0
  Attempting uninstall: azure-keyvault
    Found existing installation: azure-keyvault 1.1.0
    Uninstalling azure-keyvault-1.1.0:
      Successfully uninstalled azure-keyvault-1.1.0
  Attempting uninstall: azure-graphrbac
    Found existing installation: azure-graphrbac 0.60.0
    Uninstalling azure-graphrbac-0.60.0:
      Successfully uninstalled azure-graphrbac-0.60.0
  Attempting uninstall: azure-identity
    Found existing installation: azure-identity 1.8.0
    Uninstalling azure-identity-1.8.0:
      Successfully uninstalled azure-identity-1.8.0
  Attempting uninstall: azure-cli-core
    Found existing installation: azure-cli-core 2.34.1
    Uninstalling azure-cli-core-2.34.1:
      Successfully uninstalled azure-cli-core-2.34.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
azure-cli 2.34.1 requires azure-cli-core==2.34.1, but you have azure-cli-core 2.34.0 which is incompatible.
azure-cli 2.34.1 requires azure-graphrbac~=0.60.0, but you have azure-graphrbac 0.61.1 which is incompatible.
azure-cli 2.34.1 requires azure-keyvault~=1.1.0, but you have azure-keyvault 1.0.0a1 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-apimanagement~=3.0.0, but you have azure-mgmt-apimanagement 0.2.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-authorization~=0.61.0, but you have azure-mgmt-authorization 0.51.1 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-batch~=16.0.0, but you have azure-mgmt-batch 5.0.1 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-cdn==11.0.0, but you have azure-mgmt-cdn 3.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-compute~=25.0.0, but you have azure-mgmt-compute 26.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-containerinstance~=9.1.0, but you have azure-mgmt-containerinstance 1.4.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-containerregistry==8.2.0, but you have azure-mgmt-containerregistry 2.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-containerservice~=17.0.0, but you have azure-mgmt-containerservice 9.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-cosmosdb~=7.0.0b2, but you have azure-mgmt-cosmosdb 0.15.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-devtestlabs~=4.0, but you have azure-mgmt-devtestlabs 3.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-dns~=8.0.0, but you have azure-mgmt-dns 2.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-eventhub~=9.1.0, but you have azure-mgmt-eventhub 2.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-hdinsight~=9.0.0, but you have azure-mgmt-hdinsight 0.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-iothub==2.2.0, but you have azure-mgmt-iothub 0.7.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-keyvault==9.3.0, but you have azure-mgmt-keyvault 1.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-loganalytics~=13.0.0b2, but you have azure-mgmt-loganalytics 1.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-managementgroups~=1.0.0, but you have azure-mgmt-managementgroups 0.2.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-marketplaceordering==1.1.0, but you have azure-mgmt-marketplaceordering 0.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-network~=19.3.0, but you have azure-mgmt-network 19.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-privatedns~=1.0.0, but you have azure-mgmt-privatedns 0.1.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-rdbms~=10.0.0, but you have azure-mgmt-rdbms 1.9.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-recoveryservices~=2.0.0, but you have azure-mgmt-recoveryservices 0.4.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-recoveryservicesbackup~=4.0.0, but you have azure-mgmt-recoveryservicesbackup 0.6.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-redis~=13.1.0, but you have azure-mgmt-redis 13.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-resource==20.0.0, but you have azure-mgmt-resource 10.2.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-search~=8.0, but you have azure-mgmt-search 3.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-servicebus~=7.1.0, but you have azure-mgmt-servicebus 0.5.3 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-storage~=19.1.0, but you have azure-mgmt-storage 19.0.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-trafficmanager~=1.0.0, but you have azure-mgmt-trafficmanager 0.50.0 which is incompatible.
azure-cli 2.34.1 requires azure-mgmt-web~=6.1.0, but you have azure-mgmt-web 0.41.0 which is incompatible.
Successfully installed azure-cli-core-2.34.0 azure-common-1.1.11 azure-graphrbac-0.61.1 azure-identity-1.7.0 azure-keyvault-1.0.0a1 azure-mgmt-apimanagement-0.2.0 azure-mgmt-authorization-0.51.1 azure-mgmt-automation-1.0.0 azure-mgmt-batch-5.0.1 azure-mgmt-cdn-3.0.0 azure-mgmt-compute-26.1.0 azure-mgmt-containerinstance-1.4.0 azure-mgmt-containerregistry-2.0.0 azure-mgmt-containerservice-9.1.0 azure-mgmt-cosmosdb-0.15.0 azure-mgmt-datafactory-2.0.0 azure-mgmt-datalake-nspkg-2.0.0 azure-mgmt-devtestlabs-3.0.0 azure-mgmt-dns-2.1.0 azure-mgmt-eventhub-2.0.0 azure-mgmt-hdinsight-0.1.0 azure-mgmt-iothub-0.7.0 azure-mgmt-keyvault-1.1.0 azure-mgmt-loganalytics-1.0.0 azure-mgmt-managementgroups-0.2.0 azure-mgmt-marketplaceordering-0.1.0 azure-mgmt-network-19.1.0 azure-mgmt-notificationhubs-2.0.0 azure-mgmt-nspkg-2.0.0 azure-mgmt-privatedns-0.1.0 azure-mgmt-rdbms-1.9.0 azure-mgmt-recoveryservices-0.4.0 azure-mgmt-recoveryservicesbackup-0.6.0 azure-mgmt-redis-13.0.0 azure-mgmt-resource-10.2.0 azure-mgmt-search-3.0.0 azure-mgmt-servicebus-0.5.3 azure-mgmt-storage-19.0.0 azure-mgmt-trafficmanager-0.50.0 azure-mgmt-web-0.41.0 azure-nspkg-2.0.0 azure-storage-0.35.1
```


And this takes ~3mins to run

**Comment by l3ender** [comment]
@jdelvecchio - as mentioned in https://github.com/ansible-collections/azure/issues/130#issuecomment-1150159235, the change has been merged to dev but is not yet released. It should be included in the next release (likely to be version 1.14.0). You can install the collection from the repo's `dev` branch if you want to use the change immediately.

Hope that helps--thanks!
