### ISSUE TITLE
name 'azure_cloud' is not defined

### ISSUE THREAD

**Issue by meons** [ansible/ansible_collections_azure#1339]
##### SUMMARY

I get the following message when trying to list the inventory (`ansible-inventory -i myazure_rm.yml --graph`):
`[WARNING]:  * Failed to parse /.../myazure_rm.yml with auto plugin: name 'azure_cloud' is not defined`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

dynamic inventory plugin

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Sep 12 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection         Version
------------------ -------
azure.azcollection 2.0.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

Rocky Linux release 9.2 (Blue Onyx)

##### STEPS TO REPRODUCE

Dockerfile to build ansible image with az deps:
```
FROM rockylinux:9
RUN dnf update -y
RUN dnf install -y epel-release python3 python3-pip
RUN dnf install -y ansible-core
RUN ansible-galaxy collection install azure.azcollection
RUN pip3 install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements-azure.txt
```

myazure_rm.yml:
```yaml
---
plugin: azure_rm
auth_source: auto
subscription_id: xxx
```
Creds are set as env variables.

##### EXPECTED RESULTS

I should get the list of VMs.

##### ACTUAL RESULTS

`[WARNING]:  * Failed to parse /.../myazure_rm.yml with auto plugin: name 'azure_cloud' is not defined`

I don't get what is missing here... I followed the instructions to install azcollections and deps... (see dockerfile)

```paste below

```

**Comment by Fred-sun** [comment]
@meons How are your credential established? By credentilas_file, 'az login' or an environment variable? There was a bug that use 'az login' that was fixed in PR#1340, can you update the change and retry your test？ Thank you very much!

**Comment by meons** [comment]
> @meons How are your credential established? By credentilas_file, 'az login' or an environment variable? There was a bug that use 'az login' that was fixed in PR#1340, can you update the change and retry your test？ Thank you very much!

@Fred-sun Yep creds are established; I am using a managed identity. After I run `az login --identity` I can list VMs with `az vm list`, however the ansible dynamic inventory still fails with error `name 'azure_cloud' is not defined`...

If it can help, I tested on RHEL8 VM with older ansible version and it works...
```
Red Hat Enterprise Linux release 8.8 (Ootpa)
---
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.8 (default, May 31 2023, 10:28:59) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)]
---
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

collection list not supported, but it seems to be azcollection v1.18:
head /root/.ansible/collections/ansible_collections/azure/azcollection/CHANGELOG.md 
# Change Log

## v1.18.1 (2023-9-25)
...
```

**Comment by Fred-sun** [comment]
@meons This is a spelling error when migrating files before, it has been fixed in #1340, can you try it? Thank you!

**Comment by meons** [comment]
I tried but the issue seems to persist... Meanwhile I switched back to 1.18 azcollection and it's ok.
It worth to try on a fresh empty VM to be sure; I will setup it and try again when I have time.

**Comment by Fred-sun** [comment]
@meons Are your credentials set with 'az login' or 'credential_files'? Do you have any changes to update #1340?

**Comment by meons** [comment]
I tried az login and env variables.
Unfortunately I didn't checked the code since I trust your PR :)

**Comment by Fred-sun** [comment]
@meons If it is through 'az login' then its problem is very similar to the problem fixed by #1340, I am checking it, thanks!

**Comment by Fred-sun** [comment]
@meons Could you please provide your detailed error log? Will help solve your problems! Thank you!

**Comment by Fred-sun** [comment]
@meons After repeated testing on my part, this issue should have been resolved, and a new version will be released soon, after which I will close it. Thank you!

**Comment by Fred-sun** [comment]
@meons #1340 has been merged, I will close this issue. Thank you!

**Comment by yves-vogl** [comment]
The issue seems to be back.

Version
```
ansible [core 2.17.1]
  config file = None
  configured module search path = ['/Users/yves.vogl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/10.1.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/yves.vogl/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/10.1.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

Error
```
[WARNING]:  * Failed to parse /Users/yves.vogl/Development/example/Azure/foundation/ansible/inventory/main_azure_rm.yml with auto plugin: name 'azure_cloud' is not defined
[WARNING]:  * Failed to parse /Users/yves.vogl/Development/example/Azure/foundation/ansible/inventory/main_azure_rm.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /Users/yves.vogl/Development/example/Azure/foundation/ansible/inventory/main_azure_rm.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is reserved to provide a port.
[WARNING]: Unable to parse /Users/yves.vogl/Development/example/Azure/foundation/ansible/inventory/main_azure_rm.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
```

Inventory File
```
plugin: azure_rm
include_vm_resource_groups:
  - rg-admatch-foundation-mrpq
auth_source: auto

```

Environment
```
AZURE_CLIENT_ID=*******
AZURE_SECRET=*******
AZURE_SUBSCRIPTION_ID=*******
AZURE_TENANT=*******
```

**Comment by Fred-sun** [comment]
@yves-vogl Thank you very much for your feedback on the problems encountered.
First of all, there is no problem in my local test, but if there is no relevant dependency, there will be an error as you suggested. Could you please check your steps? Thank you!
```e.g.
    1  sudo apt update
    2  sudo apt install python3-pip
    3  sudo pip3 install ansible[azure]
    4 ansible-galaxy collection install azure.azcollection
    5 sudo pip3 install -r ~/.ansible//collections/ansible_collections/azure/azcollection/requirements.txt
    6  export AZURE_CLIENT_ID=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
    7  export AZURE_SECRET=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
    8  export AZURE_SUBSCRIPTION_ID=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
    9  export AZURE_TENANT=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
    10  vi myazure_rm.yml
    11  ansible-inventory -i myazure_rm.yml --list

**Comment by DominikBritz** [comment]
I'm also seeing this issue.

**Installation**
```
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install ansible
sudo apt install python3-pip
sudo apt install python3-venv

python3 -m venv ~/myvirtualenv
source myvirtualenv/bin/activate
pip install 'ansible[azure]'

ansible-galaxy collection install azure.azcollection --force 

pip install -r ~/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt

export AZURE_CLIENT_ID=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
export AZURE_SECRET=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
export AZURE_SUBSCRIPTION_ID=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
export AZURE_TENANT=xxxx-xxxxxxxxxxxxxxxxx-xxxxxxxxxxxx
```

**Output**
```
ansible-inventory -i myazure_rm.yml --list -vvv

ansible-inventory [core 2.16.10]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/azureuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/azureuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-inventory
  python version = 3.12.3 (main, Jul 31 2024, 17:43:48) [GCC 13.2.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /etc/ansible/ansible.cfg as config file
host_list declined parsing /home/azureuser/myazure_rm.yml as it did not pass its verify_file() method
script declined parsing /home/azureuser/myazure_rm.yml as it did not pass its verify_file() method
redirecting (type: inventory) ansible.builtin.azure_rm to azure.azcollection.azure_rm
Using inventory plugin 'ansible_collections.azure.azcollection.plugins.inventory.azure_rm' to process inventory source '/home/azureuser/myazure_rm.yml'
toml declined parsing /home/azureuser/myazure_rm.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /home/azureuser/myazure_rm.yml with auto plugin: name 'azure_cloud' is not defined
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/auto.py", line 59, in parse
    plugin.parse(inventory, loader, path, cache=cache)
  File "/home/azureuser/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 232, in parse
    self._credential_setup()
  File "/home/azureuser/.ansible/collections/ansible_collections/azure/azcollection/plugins/inventory/azure_rm.py", line 267, in _credential_setup
    self.azure_auth = AzureRMAuth(**auth_options)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/azureuser/.ansible/collections/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 1472, in __init__
    self._cloud_environment = azure_cloud.AZURE_PUBLIC_CLOUD  # SDK default
                              ^^^^^^^^^^^
[WARNING]:  * Failed to parse /home/azureuser/myazure_rm.yml with yaml plugin: Plugin configuration YAML file, not YAML inventory
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/yaml.py", line 114, in parse
    raise AnsibleParserError('Plugin configuration YAML file, not YAML inventory')
[WARNING]:  * Failed to parse /home/azureuser/myazure_rm.yml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed,
this character is reserved to provide a port.
  File "/usr/lib/python3/dist-packages/ansible/inventory/manager.py", line 293, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
  File "/usr/lib/python3/dist-packages/ansible/plugins/inventory/ini.py", line 138, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /home/azureuser/myazure_rm.yml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
```

**Comment by microHoffman** [comment]
I'm also encountering this issue... any ideas?

**Comment by Fred-sun** [comment]
@microHoffman I execute locally and do not encounter the problem you mentioned. In order to better solve this problem, could you please open an new issue and provide detailed  (playbook, azure.azcollection) information to solve this problem? In addition, you need to provide the environment, pip3 list and other information.Thank you!

**Comment by kyr0** [comment]
@Fred-sun  Same issue here. 

`myazure_rm.yml`
```
plugin: azure_rm
include_vm_resource_groups:
  - some-rg
auth_source: auto
keyed_groups:
 - key: tags.applicationRole
```

`env` snippet (def. exported)
```
AZURE_SUBSCRIPTION_ID=***
AZURE_SECRET=***
AZURE_TENANT=***
AZURE_CLIENT_ID=***
```

Error output:

```
ansible-inventory [core 2.18.1]
  config file = None
  configured module search path = ['/Users/admin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /Users/admin/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible-inventory
  python version = 3.13.1 (main, Dec  3 2024, 17:59:52) [Clang 16.0.0 (clang-1600.0.26.4)] (/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/bin/python)
  jinja version = 3.1.5
  libyaml = True
No config file found; using defaults
host_list declined parsing /***/infrastructure/azure/myazure_rm.yml as it did not pass its verify_file() method
script declined parsing /***/infrastructure/azure/myazure_rm.yml as it did not pass its verify_file() method
toml declined parsing /***/infrastructure/azure/myazure_rm.yml as it did not pass its verify_file() method
[WARNING]:  * Failed to parse /***/infrastructure/azure/myazure_rm.yml with auto plugin:
We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line
1 column 2 (char 1)  Syntax Error while loading YAML.   but found another document. expected a single document in
the stream   in "<unicode string>", line 1, column 1 but found another document   in "<unicode string>", line 2,
column 1  The error appears to be in '/***/infrastructure/azure/myazure_rm.yml': line 2,
column 1, but may be elsewhere in the file depending on the exact syntax problem.  The offending line appears to
be:  [default] --- ^ here
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/inventory/manager.py", line 292, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/plugins/inventory/auto.py", line 39, in parse
    config_data = loader.load_from_file(path, cache='none')
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/parsing/dataloader.py", line 105, in load_from_file
    parsed_data = self.load(data=file_data, file_name=file_name, show_content=show_content, json_only=json_only)
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/parsing/dataloader.py", line 78, in load
    return from_yaml(data, file_name, show_content, self._vault.secrets, json_only=json_only)
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/parsing/utils/yaml.py", line 80, in from_yaml
    _handle_error(json_exc, yaml_exc, file_name, show_content)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/parsing/utils/yaml.py", line 41, in _handle_error
    raise AnsibleParserError(n_err_msg, obj=err_obj, show_content=show_content, orig_exc=yaml_exc)
[WARNING]:  * Failed to parse /***/infrastructure/azure/myazure_rm.yml with yaml plugin:
We were unable to read either as JSON nor YAML, these are the errors we got from each: JSON: Expecting value: line
1 column 2 (char 1)  Syntax Error while loading YAML.   but found another document. expected a single document in
the stream   in "<unicode string>", line 1, column 1 but found another document   in "<unicode string>", line 2,
column 1  The error appears to be in '/***/infrastructure/azure/myazure_rm.yml': line 2,
column 1, but may be elsewhere in the file depending on the exact syntax problem.  The offending line appears to
be:  [default] --- ^ here
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/inventory/manager.py", line 292, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/plugins/inventory/yaml.py", line 106, in parse
    raise AnsibleParserError(e)
[WARNING]:  * Failed to parse /***/infrastructure/azure/myazure_rm.yml with ini plugin:
Invalid host pattern '---' supplied, '---' is normally a sign this is a YAML file.
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/inventory/manager.py", line 292, in parse_source
    plugin.parse(self._inventory, self._loader, source, cache=cache)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/ansible/11.1.0_1/libexec/lib/python3.13/site-packages/ansible/plugins/inventory/ini.py", line 137, in parse
    raise AnsibleParserError(e)
[WARNING]: Unable to parse /***/infrastructure/azure/myazure_rm.yml as an inventory
source
[WARNING]: No inventory was parsed, only implicit localhost is available
```

**Comment by dtvlinux** [comment]
It is not a part of the requirements.txt  for the azcollection but the issue was resolved after running `pip install "ansible[azure]"`
