### ISSUE TITLE
Azure Resource Manager inventory plugin: Allow setting resources groups to include at runtime

### ISSUE THREAD

**Issue by christophetd** [ansible/ansible_collections_azure#152]
##### SUMMARY

Allow setting resources groups to include at runtime via environment variable

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

[Azure Resource Manager inventory plugin](https://docs.ansible.com/ansible/latest/plugins/inventory/azure_rm.html)

##### ADDITIONAL INFORMATION

Currently, the Azure resource groups to include in the inventory needs to be provided as part of the provider's configuration file:

```yaml
plugin: azure_rm
auth_source: cli
include_vm_resource_groups:
- my-rg1
- my-rg2
```

This is a quite strong limitation because it doesn't allow you to dynamically specify these groups at runtime. Also, the [Python script](https://github.com/ansible/ansible/blob/stable-2.9/contrib/inventory/azure_rm.py) provided for dynamic inventories in the previous Ansible versions [_did_](https://github.com/ansible/ansible/blob/stable-2.9/contrib/inventory/azure_rm.py#L137) allow to set an environment variable to control this behaviour.

Sample usage:
``` 
ANSIBLE_AZURE_INCLUDE_VM_RESOURCE_GROUPS=my-rg1,my-rg2
ansible-playbook -i azure_rm.yml ...
```

**Comment by Fred-sun** [comment]
@christophetd Thanks for you submit the issue. we will investigate those feature！ Thank you very much!

**Comment by christophetd** [comment]
Thanks, looking forward to it!

**Comment by Liquidmantis** [comment]
@Fred-sun any updates on this?  I'm hitting the same issue of needing to specify the resource groups at runtime in pipelines.  It doesn't appear that variables of any form are evaluated for `include_vm_resource_groups` and I'm thinking I'm going to be forced into dynamically inserting into the inventory file.

**Comment by Fred-sun** [comment]
@Liquidmantis Yes, if we want to include VMS under a certain resource group, it is necessary to enable dynamsterting into the inventory file. Thank you very much!

**Comment by Fred-sun** [comment]
> Thanks, looking forward to it!

@christophetd Yes, if you want to dynamically obtain VMS under a resource group, you need to obtain VMS from the Dynamic Inventory method. Thank you very much!

**Comment by joshlrogers** [comment]
Is there any update on this? This would be tremendously helpful for deploying to multiple environments which we segregate by resource groups.

**Comment by Fred-sun** [comment]
fixes by #975

**Comment by HarishHary** [comment]
@Fred-sun any update on your MR? Thanks for your work!

**Comment by Fred-sun** [comment]
@HarishHary It has fixed by #975, and this PR is ready, It will be merged as soon as possible! Thank you very much!

**Comment by HarishHary** [comment]
Hello @Fred-sun, thanks for the fix again! Do you know when a new release is planned for the plugin? Still can't use it in production.

**Comment by PiotrWachulec** [comment]
Hey! @HarishHary we are also waiting for this, our issue: [Cannot pass variables into the dynamic inventory configuration](https://github.com/ansible-collections/azure/issues/1049).

@Fred-sun any plans for releasing?

**Comment by Fred-sun** [comment]
@PiotrWachulec @HarishHary Recently we want to upgrade a package, they will be released together, the upgrade is under way, thank you!

**Comment by PiotrWachulec** [comment]
Great, we are waiting! :)
