### ISSUE TITLE
azure_rm_manageddisk fails with error "module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'ManagedDiskParameters'" 

### ISSUE THREAD

**Issue by mlacko64** [ansible/ansible_collections_azure#1751]
##### SUMMARY

Hello,
I am using module azure_rm_manageddisk to attach disks to existing VM in my playbook (there were no changes to playbook for longer time). I run it today (after few weeks) and it failed with error:

```AttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'ManagedDiskParameters'```

Example of my failing playbook task is here:
```
- hosts: localhost

  vars:
    sds_nodes:
      - node_name: sds01.bmdev01.dev-azure.baremetal.xyz
      - node_name: sds02.bmdev01.dev-azure.baremetal.xyz
      - node_name: sds03.bmdev01.dev-azure.baremetal.xyz

  tasks:
    - name: Attach portworx kvdb disk to VM
      azure_rm_manageddisk:
        name: "{{item.node_name}}-pxkvdb"
        location: westus3
        resource_group: bmdev01
        disk_size_gb: 128
        storage_account_type: Premium_LRS
        zone: "{{ansible_loop.index}}"
        managed_by: "{{item.node_name}}"
      loop: "{{sds_nodes}}"
      loop_control:
        extended: yes
      delegate_to: localhost

```
Full output of playbook is attached
[run.txt](https://github.com/user-attachments/files/17618490/run.txt)

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_manageddisk

##### ANSIBLE VERSION

```
ansible-playbook [core 2.15.12]
  config file = None
  configured module search path = ['/home/ocpadmin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ocpadmin/ansible/lib/python3.9/site-packages/ansible
  ansible collection location = /home/ocpadmin/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ocpadmin/ansible/bin/ansible-playbook
  python version = 3.9.18 (main, Jan 24 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] (/home/ocpadmin/ansible/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

##### COLLECTION VERSION

```
(ansible) [ocpadmin@bastion ~]$ ansible-galaxy collection list

# /home/ocpadmin/.ansible/collections/ansible_collections
Collection                    Version
----------------------------- -------
azure.azcollection            3.0.0

# /home/ocpadmin/ansible/lib/python3.9/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
amazon.aws                    6.5.0
ansible.netcommon             5.3.0
ansible.posix                 1.5.4
ansible.utils                 2.12.0
ansible.windows               1.14.0
arista.eos                    6.2.2
awx.awx                       22.7.0
azure.azcollection            1.19.0
check_point.mgmt              5.1.1
chocolatey.chocolatey         1.5.1
cisco.aci                     2.8.0
cisco.asa                     4.0.3
cisco.dnac                    6.9.0
cisco.intersight              1.0.27
cisco.ios                     4.6.1
cisco.iosxr                   5.0.3
cisco.ise                     2.6.2
cisco.meraki                  2.17.0
cisco.mso                     2.5.0
cisco.nso                     1.0.3
cisco.nxos                    4.4.0
cisco.ucs                     1.10.0
cloud.common                  2.1.4
cloudscale_ch.cloud           2.3.1
community.aws                 6.4.0
community.azure               2.0.0
community.ciscosmb            1.0.7
community.crypto              2.16.1
community.digitalocean        1.24.0
community.dns                 2.6.4
community.docker              3.4.11
community.fortios             1.0.0
community.general             7.5.2
community.google              1.0.0
community.grafana             1.6.1
community.hashi_vault         5.0.1
community.hrobot              1.8.2
community.libvirt             1.3.0
community.mongodb             1.6.3
community.mysql               3.8.0
community.network             5.0.2
community.okd                 2.3.0
community.postgresql          2.4.3
community.proxysql            1.5.1
community.rabbitmq            1.2.3
community.routeros            2.11.0
community.sap                 1.0.0
community.sap_libs            1.4.1
community.skydive             1.0.0
community.sops                1.6.7
community.vmware              3.11.1
community.windows             1.13.0
community.zabbix              2.2.0
containers.podman             1.11.0
cyberark.conjur               1.2.2
cyberark.pas                  1.0.23
dellemc.enterprise_sonic      2.2.0
dellemc.openmanage            7.6.1
dellemc.powerflex             1.9.0
dellemc.unity                 1.7.1
f5networks.f5_modules         1.27.1
fortinet.fortimanager         2.3.0
fortinet.fortios              2.3.4
frr.frr                       2.0.2
gluster.gluster               1.0.2
google.cloud                  1.3.0
grafana.grafana               2.2.3
hetzner.hcloud                1.16.0
hpe.nimble                    1.1.4
ibm.qradar                    2.1.0
ibm.spectrum_virtualize       1.12.0
ibm.storage_virtualize        2.1.0
infinidat.infinibox           1.3.12
infoblox.nios_modules         1.5.0
inspur.ispim                  1.3.0
inspur.sm                     2.3.0
junipernetworks.junos         5.3.1
kubernetes.core               2.4.0
lowlydba.sqlserver            2.2.2
microsoft.ad                  1.4.1
netapp.aws                    21.7.1
netapp.azure                  21.10.1
netapp.cloudmanager           21.22.1
netapp.elementsw              21.7.0
netapp.ontap                  22.8.3
netapp.storagegrid            21.11.1
netapp.um_info                21.8.1
netapp_eseries.santricity     1.4.0
netbox.netbox                 3.15.0
ngine_io.cloudstack           2.3.0
ngine_io.exoscale             1.1.0
ngine_io.vultr                1.1.3
openstack.cloud               2.2.0
openvswitch.openvswitch       2.1.1
ovirt.ovirt                   3.2.0
purestorage.flasharray        1.24.0
purestorage.flashblade        1.14.0
purestorage.fusion            1.6.0
sensu.sensu_go                1.14.0
servicenow.servicenow         1.0.6
splunk.es                     2.1.2
t_systems_mms.icinga_director 1.33.1
telekom_mms.icinga_director   1.35.0
theforeman.foreman            3.15.0
vmware.vmware_rest            2.3.1
vultr.cloud                   1.11.0
vyos.vyos                     4.1.0
wti.remote                    1.0.5
```

##### CONFIGURATION

```
(ansible) [ocpadmin@bastion ~]$ ansible-config dump --only-changed
CONFIG_FILE() = None
(ansible) [ocpadmin@bastion ~]$
```

##### OS / ENVIRONMENT

Azure Linux VM
```
(ansible) [ocpadmin@bastion ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux release 9.4 (Plow)
(ansible) [ocpadmin@bastion ~]$
```
Ansible virtual environment installed with:
```
pip3 install virtualenv
python3 -m virtualenv /home/ocpadmin/ansible
source /home/ocpadmin/ansible/bin/activate
pip3 install dnspython openshift netaddr Babel bcrypt cffi cryptography oauthlib jsonschema jmespath ansible ansible-runner
ansible-galaxy collection install azure.azcollection --force
pip3 install -r /home/ocpadmin/.ansible/collections/ansible_collections/azure/azcollection/requirements.txt
deactivate
```

##### STEPS TO REPRODUCE

```
Run playbook as provided in example
```

##### EXPECTED RESULTS

Disks are created and attached to VMs

##### ACTUAL RESULTS

Disks are created and module fails. They are not attached to VMs.

**Comment by Fred-sun** [comment]
@mlacko64 Fixed in #1756

**Comment by sean-freeman** [comment]
@Fred-sun This is a critical bug for IaaS, why has `3.0.1` not been released?

**Comment by Fred-sun** [comment]
@sean-freeman We will release v3.0.1 as soon as possible! Thank you!

**Comment by sean-freeman** [comment]
@Fred-sun Personally, I would suggest you revisit your release schedule strategy. This is such a severe bug reported and fixed days after the last breaking change release, it should have immediately triggered a patch release `3.0.1` instead of bundling additional changes thereafter that slows regression testing and slows a release of a critically required fix.

**Comment by Fred-sun** [comment]
@sean-freeman We will push forward the release tomorrow, thank you!

**Comment by sean-freeman** [comment]
@Fred-sun Please do not publicly commit to a date, if you do not intend to meet it

**Comment by Fred-sun** [comment]
@sean-freeman Yes, I will push forward with the release, and I will notify you once it is released! Thank you!

**Comment by xuzhang3** [comment]
@sean-freeman  sorry for the delay.  `v3.1.0` has been released, you can pull the latest release from galaxy

**Comment by rewi1701** [comment]
Hello everybody,
i still get same error mentioned above.
But not  during  the first run of my Ansible Playbook (which deploys a new VM plus attaching a Disc).
The error happens while i re-run the Playbook - e.g. to change the Disc size.
I feels to me that the Bug is not 100% resolved.
Any ideas?
Was a second run (re-run) of a skript/playbook with this new released azcollection?

Thank you so much for your support!


ERROR >>>>>

TASK [azure : Create datadisk-0] ***************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'Ca                                         chingTypes'
fatal: [ansibletest -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1734708858.9454334-73-8140632685717                                         8/AnsiballZ_azure_rm_manageddisk.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1734708858.9454334-73-81406326857178/AnsiballZ_azure_rm_manageddisk.p                                         y\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1734708858.9454334-73-81406326857178/AnsiballZ_azure_rm_mana                                         geddisk.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', init_globals=dict(_module_fqn=                                         'ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runp                                         y>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_e_bxgl4b/ansible_azure_rm_manageddisk_paylo                                         ad.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 763, in <module>\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_e_bxgl4b/ansible_                                         azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 759, in main\n  File \"/tmp/ansible_azure_rm_manageddisk_pay                                         load_e_bxgl4b/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 498, in __init__\n  File \"/tmp/ansibl                                         e_azure_rm_manageddisk_payload_e_bxgl4b/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 482, in __in                                         it__\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_e_bxgl4b/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddi                                         sk.py\", line 571, in exec_module\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_e_bxgl4b/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugi                                         ns/modules/azure_rm_manageddisk.py\", line 749, in is_attach_caching_option_different\nAttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes                                         '\n", "module_stdout": "", "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error", "rc": 1}

**Comment by Fred-sun** [comment]
@rewi1701 It has added in dev branch and will release in next version. Thanks!

**Comment by rewi1701** [comment]
Many Thanks! @Fred-sun

**Comment by rewi1701** [comment]
Any idea, when the new version will be released? ( i hope somehow in the next upcoming days)
I really need a working version.
Thanks

**Comment by Fred-sun** [comment]
@rewi1701 Has been released, version v3.1.0, thank you!

**Comment by rewi1701** [comment]
**Hello,**

seems that the bug still exists. Still running in errors. Spent alot of time in getting my Ansible Playbook running.
Second run aborts always when it executes the "azure_rm_manageddisk" module. Having no ideas anymore at the moment :-( 

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible-tmp-1736438947.2086124-239-41750848754336/AnsiballZ_azure_rm_manageddisk.py", line 107, in <module>
    _ansiballz_main()
  File "/tmp/ansible-tmp-1736438947.2086124-239-41750848754336/AnsiballZ_azure_rm_manageddisk.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/tmp/ansible-tmp-1736438947.2086124-239-41750848754336/AnsiballZ_azure_rm_manageddisk.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 763, in <module>
  File "/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 759, in main
  File "/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 498, in __init__
  File "/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 482, in __init__
  File "/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 571, in exec_module
  File "/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 749, in is_attach_caching_option_different
AttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes'
fatal: [ansibletest -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible-tmp-1736438947.2086124-239-41750848754336/AnsiballZ_azure_rm_manageddisk.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/tmp/ansible-tmp-1736438947.2086124-239-41750848754336/AnsiballZ_azure_rm_manageddisk.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/tmp/ansible-tmp-1736438947.2086124-239-41750848754336/AnsiballZ_azure_rm_manageddisk.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 763, in <module>\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 759, in main\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 498, in __init__\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 482, in __init__\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 571, in exec_module\n  File \"/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 749, in is_attach_caching_option_different\n**AttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes'**\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE: No start of json char found\nSee stdout/stderr for the exact error",
    "rc": 1
}

Was the playbook / module  running properly after your bugfixing and tests?
How did you check it?

Thanks

**Comment by Fred-sun** [comment]
@rewi1701 Thank you for reporting this issue, but from your error message, you are not up to date with the latest code. Because the location of your error is different from the latest code. Thank you!

```e.g.
"/tmp/ansible_azure_rm_manageddisk_payload_gb0_v0gq/ansible_azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py", line 749, in is_attach_caching_option_different\nAttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes'\n",
Errors:
```
```e.g.
Code:
832             self.log('Did not find managed disk')
833
834     def is_attach_caching_option_different(self, vm_name, disk):
835         resp = False
836         if vm_name:
837             vm = self._get_vm(self.resource_group, vm_name)

**Comment by rewi1701** [comment]
Okay, i will check it twice.
Thank you so much for quick response and help!

**Comment by dbijoc** [comment]
Hi all,

I'm facing the same issue as @rewi1701.
The 1st execution of the playbook is running fine. Disks are created and attached to the VMs.
But when running the playbook a 2nd time (without changing any values/variables) I got this error : 

`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes'
failed: [srv-joc-patr3 -> localhost] (item=1) => {"ansible_loop_var": "item", "changed": false, "item": "1", "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1738615111.8168733-20725-30593073555096/AnsiballZ_azure_rm_manageddisk.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1738615111.8168733-20725-30593073555096/AnsiballZ_azure_rm_manageddisk.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1738615111.8168733-20725-30593073555096/AnsiballZ_azure_rm_manageddisk.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_y0cmityl/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 763, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_y0cmityl/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 759, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_y0cmityl/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 498, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_y0cmityl/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 482, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_y0cmityl/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 571, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_y0cmityl/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 749, in is_attach_caching_option_different\nAttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}`

I'm using the azure.azcollection version 3.1.0.

@Fred-sun : any hint ? Do you confirm that the bug is not fully fixed ?

Thank you for your help !

**Comment by rewi1701** [comment]
@dbijoc :
Hi dbijoc, interessting to hear that someone else runs into the same issue. Thought all the time, i am the only one ;-)

BTW: I am struggeling with the same issue still!
Second playbook run crashes with the error mentioned in above comments (managedisk module)

I am def. use the highest available azure.azcollection version 3.1.0

@Fred-sun : Any idea?
Can we support you anyway?

Thank you so much!

**Comment by MallocArray** [comment]
Looks to be related to #1811

**Comment by rewi1701** [comment]
Any update?

**Comment by Fred-sun** [comment]
@rewi1701 This requirement has been solved and published in version v3.2.0. I am dealing with the problem of meters (#1811) you mentioned, thank you!

**Comment by rewi1701** [comment]
Thanks!
Will check test and run my playbooks. ...
Will let you know

**Comment by dbijoc** [comment]
Hi,

I have tested with v3.2.0 but I still have the same issue as before. 
1st run is ok, 2nd run is failing : 

```
TASK [yak.core.os_storage : Create and attach the managed disk to VM] **********
Monday 17 February 2025  10:49:18 +0100 (0:00:05.363)       0:00:10.224 ******* 
 [started TASK: yak.core.os_storage : Create and attach the managed disk to VM on t-az-ol87-lvm-1]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes'
failed: [t-az-ol87-lvm-1 -> localhost] (item=1) => {
    "ansible_loop_var": "item",
    "changed": false,
    "item": "1",
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1739785759.005885-25057-115624596333952/AnsiballZ_azure_rm_manageddisk.py\", line 107, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1739785759.005885-25057-115624596333952/AnsiballZ_azure_rm_manageddisk.py\", line 99, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1739785759.005885-25057-115624596333952/AnsiballZ_azure_rm_manageddisk.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', init_globals=dict(_module_fqn='ansible_collections.azure.azcollection.plugins.modules.azure_rm_manageddisk', _modlib_path=modlib_path),\n  File \"/usr/lib/python3.9/runpy.py\", line 210, in run_module\n    return _run_module_code(code, init_globals, run_name, mod_spec)\n  File \"/usr/lib/python3.9/runpy.py\", line 97, in _run_module_code\n    _run_code(code, mod_globals, init_globals,\n  File \"/usr/lib/python3.9/runpy.py\", line 87, in _run_code\n    exec(code, run_globals)\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_98ah_euc/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 853, in <module>\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_98ah_euc/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 849, in main\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_98ah_euc/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 571, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_98ah_euc/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py\", line 482, in __init__\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_98ah_euc/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 648, in exec_module\n  File \"/tmp/ansible_azure.azcollection.azure_rm_manageddisk_payload_98ah_euc/ansible_azure.azcollection.azure_rm_manageddisk_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_manageddisk.py\", line 839, in is_attach_caching_option_different\nAttributeError: module 'azure.mgmt.compute.v2023_04_02.models' has no attribute 'CachingTypes'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

@rewi1701 : what about your test ?

Thank you !

**Comment by rewi1701** [comment]
Hi,
sorry for the late answer.
Yesterday i got back to this topic and test it.
It is still  not working  at my end
I involved another colleague in this issue and we spend alot of time to troubleshoot.
I will post some more hints and information soon.
Maybe i will open a new issue, because this one has been closed to early
