### ISSUE TITLE
Standard SKU IPv6 requires static allocation method

### ISSUE THREAD

**Issue by aardbol** [ansible/ansible_collections_azure#192]
##### SUMMARY

IPv6 with Standard SKU only accepts allocation method Static, but the allocation_method option is ignored when set

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

azure_rm_publicipaddress

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
config file = /etc/ansible/ansible.cfg
configured module search path = [u'/home/ik/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /home/ik/.local/lib/python2.7/site-packages/ansible
executable location = /home/ik/.local/bin/ansible
python version = 2.7.18 (default, Apr 23 2020, 22:32:06) [GCC 9.3.0]
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
    - name: Create IPv6 public IP
      azure_rm_publicipaddress:
        name: my-ipv6
        resource_group: "{{ resource_grp }}"
        version: ipv6
        sku: Standard
        allocation_method: static
```

##### ACTUAL RESULTS

```paste below

```

**Comment by Fred-sun** [comment]
@aardbol This problem with https://github.com/ansible-collections/azure/issues/110 repeat, was fixed with what is https://github.com/ansible-collections/azure/pull/125, you can try this PR whether to repair the problem you encountered? Thank you very much!

**Comment by aardbol** [comment]
@Fred-sun I modified the `/usr/lib/python3.8/site-packages/ansible/modules/cloud/azure/azure_rm_publicipaddress.py`  file on my computer with that change and noticed that it didn't solve the issue. The same error is shown:
`
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating my-ipv6 - Azure Error: StandardSkuPublicIPAddressesMustBeStatic\nMessage: Standard sku publicIp /subscriptions/xxx/resourceGroups/myrgrp/providers/Microsoft.Network/publicIPAddresses/my-ipv6 must have AllocationMethod set to Static."} 
`

Task:
```
    - name: Create IPv6 public IP
      azure_rm_publicipaddress:
        name: my-ipv6
        resource_group: "{{ resource_grp }}"
        sku: standard
        allocation_method: static
        version: ipv6
```

Also, since Standard SKU doesn't support dynamic IPs, the Static allocation_method should be default.

**Comment by aardbol** [comment]
Added fix to PR #125

**Comment by Fred-sun** [comment]
@aardbol Thanks for your update! I will reinvestigate the logical rules of IPV4 and IPV6 design. Thank you very much!
