### ISSUE TITLE
Centralize the auth process and allow modules to include / exclude specific methods when needed

### ISSUE THREAD

**Issue by uda** [ansible/ansible_collections_azure#245]
##### SUMMARY
Currently every module can implement their own auth method and ignore the built-in Azure CLI support or provided credentials.

Ansible is meant for automation, so if I run `az login` on a machine (locally or remote) I expect ALL ansible azure modules to accept the permissions the logged-in user has and not randomly get stuck with a module ignoring Azure CLI creds and requiring me to provide credentials I don't want to pass in the playbook role or even in the vault (I prefer to rely on the current user's permissions than on globally shared access).

If I want to use specific credentials, that should be an option, not a requirement.

The essence of this proposal is to enforce centralized authenticated client API in ALL contributed modules, while allowing to ADD direct or custom auth, not replace unless absolutely necessary.
If a module, for some weird reason, requires only non Azure CLI or environment variable credenmtials, that should be reasoned and documented, and the module should be specially marked.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
I got stuck on `azure_rm_keyvaultsecret_info` but it is relevant to others as well

##### ADDITIONAL INFORMATION
This is really frustrating, especially given that auth issues are repeatedly repeatedly attached with the `medium_priority` label.

No, Security is not a medium priority, it is a deal-breaker, it is the difference between a working solution and something that doesn't work.
If a module works only if I provide globally shared credentials, from automation perspective it doesn't work.

**Comment by Fred-sun** [comment]
@uda Thank you for submitting this question! Are you having any problems? Can you give your playbook and error information? This can solve this problem more effectively! Thank you!

**Comment by uda** [comment]
Here is what I got when trying to fetch a secret (There is no lookup plugin, yet, and I know there are workarounds like `shell: az keyvault secret show ...`, but that's just another mountain of issues waiting to happen)

The relevant ansible representation:
```yaml
---
- name: Check Azure KeyVault
  hosts: localhost
  connection: local

  collections:
    - azure.azcollection

  tasks:
    - azure_rm_keyvaultsecret_info:
        vault_uri: 'https://myVaultName.vault.azure.net/'
        name: vaultSecretName
      register: myValutSecret
```

The step stderr:
```shell
Your credentials class does not support session injection. Performance will not be at the maximum.
Traceback (most recent call last):
  File "/home/username/.ansible/tmp/ansible-tmp-1600005683.3739278-3332290-117406668798624/AnsiballZ_azure_rm_keyvaultsecret_info.py", line 102, in <module>
    _ansiballz_main()
  File "/home/username/.ansible/tmp/ansible-tmp-1600005683.3739278-3332290-117406668798624/AnsiballZ_azure_rm_keyvaultsecret_info.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/username/.ansible/tmp/ansible-tmp-1600005683.3739278-3332290-117406668798624/AnsiballZ_azure_rm_keyvaultsecret_info.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.azure.azcollection.plugins.modules.azure_rm_keyvaultsecret_info', init_globals=None, run_name='__main__', alter_sys=True)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 207, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_wxgio56l/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 434, in <module>
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_wxgio56l/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 430, in main
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_wxgio56l/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 242, in __init__
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_wxgio56l/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/module_utils/azure_rm_common.py", line 436, in __init__
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_wxgio56l/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 268, in exec_module
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_wxgio56l/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 372, in list_secrets
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/paging.py", line 143, in __next__
    self.advance_page()
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/paging.py", line 129, in advance_page
    self._response = self._get_next(self.next_link)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/azure/keyvault/key_vault_client.py", line 1867, in internal_paging
    response = self._client.send(
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/service_client.py", line 336, in send
    pipeline_response = self.config.pipeline.run(request, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 197, in run
    return first_node.send(pipeline_request, **kwargs)  # type: ignore
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 72, in send
    return self.next.send(request, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 137, in send
    return self.next.send(request, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/pipeline/__init__.py", line 150, in send
    response = self.next.send(request, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/pipeline/requests.py", line 193, in send
    self.driver.send(request.http_request, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/universal_http/requests.py", line 333, in send
    return super(RequestsHTTPSender, self).send(request, **requests_kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/msrest/universal_http/requests.py", line 139, in send
    response = session.request(
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/sessions.py", line 650, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/requests/hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/azure/keyvault/custom/key_vault_authentication.py", line 146, in _handle_401
    security = self._get_message_security(prep, challenge)
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/azure/keyvault/custom/key_vault_authentication.py", line 169, in _get_message_security
    token = AccessToken(*self._callback(challenge.get_authorization_server(),
  File "/home/username/.pyenv/versions/3.8.5/lib/python3.8/site-packages/azure/keyvault/custom/key_vault_authentication.py", line 60, in _auth_callback_compat
    return self._user_callback(server, resource, scope) \
  File "/tmp/ansible_azure_rm_keyvaultsecret_info_payload_wxgio56l/ansible_azure_rm_keyvaultsecret_info_payload.zip/ansible_collections/azure/azcollection/plugins/modules/azure_rm_keyvaultsecret_info.py", line 283, in auth_callback
KeyError: 'client_id'
```

* I've tried with python 3.6 as well, same result.
* I've tested `azure_rm_keyvault_info` with success, but I couldn't put my finger on the differences between them in auth aspects

**Comment by Fred-sun** [comment]
@uda Thanks for your info! I will recheck it!

**Comment by UnwashedMeme** [comment]
This issue just wasted several hours of work for me as well. This is also described in #134 and #178.

Looking at the [release notes for azure-mgmt-resource](https://pypi.org/project/azure-mgmt-resource/) it looks like everything has recently (several months ago in the June release) converted to using the [azure-identity](https://pypi.org/project/azure-identity/) library which has a default chain for of pulling credentials from multiple locations as well as a configurable chain that I think this project could use well.

Also I note that [azure-keyvault](https://pypi.org/project/azure-keyvault/) is currently 4.1.0. This project references `azure-keyvault==1.0.0a1`.

**Comment by lisaplapla** [comment]
@Fred-sun Any update regarding this issue?
We're also facing the issue described in #178 
The fact that this project requires very old versions of the libraries tends to wreak havoc if one is using the latest version of az cli, and forces to run everything ansible related in a venv, adding another layer of complexity. Any reasons why the requirement list is not updated to work with more recent versions?

**Comment by Fiury00** [comment]
Any updates on this issue? I am able to use azure_rm_subnet_info but not azure_rm_keyvaultsecret_info.

**Comment by Fred-sun** [comment]
@uda @Fiury00 @lisaplapla I have not had any problems with the latest version of Azure Collection.  Can you upgrade to latest to retry(may fixed by #525). Thank you very much!
```e.g.
ansible-galaxy collection install azure.azcollection --force
```
```e.g.
        "secrets": [
            {
                "attributes": {
                    "created": "2021-07-01T01:16:55+00:00",
                    "enabled": true,
                    "expires": null,
                    "not_before": null,
                    "recovery_level": "Recoverable+Purgeable",
                    "updated": "2021-07-01T01:16:55+00:00"
                },
                "content_type": "Content Type Secret",
                "secret": "mysecret",
                "sid": "https://xxx/secrets/testsecret/xxxx",
                "tags": {
                    "delete": "on-exit",
                    "testing": "test"
                },
                "version": "eca8f76e4bd0451ab114805f0d7eb7f8"
            }
        ]

**Comment by uda** [comment]
Hi, didn't have the chance to check again until today.

So I've updated to 1.7.0 and refreshed the dependencies and I am still getting the `KeyError` for missing `client_id`.

I created a fresh python environment, installed latest stable ansible, azure requirements and ran the playbook again, yet still the annoying error, then I checked the installed libraries, and `azure-keyvault` library s still set to `1.0.0a1`, so I shouldn't have even tried :disappointed: 

```
> pip freeze | grep keyvault
azure-keyvault==1.0.0a1
azure-mgmt-keyvault==1.1.0

> ansible --version
ansible [core 2.11.3] 
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.pyenv/versions/3.9.6/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.pyenv/versions/3.9.6/bin/ansible
  python version = 3.9.6 (default, Jul 20 2021, 23:42:12) [GCC 9.3.0]
  jinja version = 3.0.1
  libyaml = True

> ansible-galaxy collection list
# /home/user/.ansible/collections/ansible_collections
Collection           Version
-------------------- -------
azure.azcollection   1.7.0  
community.kubernetes 1.1.1  

# /home/user/.pyenv/versions/3.9.6/lib/python3.9/site-packages/ansible_collections
Collection                    Version
----------------------------- -------
... [builtin collections]
azure.azcollection            1.7.0  
... [builtin collections]
```

**Comment by stobias123** [comment]
Also running into significant challenges using azure keyvault. Major roadblock for our use of ansible

**Comment by Fred-sun** [comment]
duplicate with #134 , fixes by #770
