### ISSUE TITLE
Error updating virtual machine: Required parameter 'osProfile' is missing

### ISSUE THREAD

**Issue by planetmarshall** [ansible/ansible_collections_azure#378]
##### SUMMARY
Receiving the following error when updating a virtual machine scale set:

```
Error creating or updating virtual machine vmsslinuxspool - Azure Error: InvalidParameter\nMessage: Required parameter 'osProfile' is missing (null).\nTarget: osProfile
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
`azure_rm_virtualmachinescaleset`

##### ANSIBLE VERSION
```
ansible 2.10.4
  config file = None
  configured module search path = ['/home/andrew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/andrew/projects/fuel3d/build-environment/ansible/.venv/lib/python3.8/site-packages/ansible
  executable location = /home/andrew/projects/fuel3d/build-environment/ansible/.venv/bin/ansible
  python version = 3.8.3 (default, Jul  8 2020, 20:42:45) [Clang 9.0.0 (tags/RELEASE_900/final)]

```

##### OS / ENVIRONMENT

Ubuntu 20.04 LTS

##### STEPS TO REPRODUCE

```yaml
- name: Update scale set image reference
  hosts: localhost
  collections:
  - azure.azcollection
  connection: local
  vars:
    vmss_name: "{{ lookup('env', 'VMSS_NAME') }}"
    image_name: "{{ lookup('env', 'IMAGE_NAME') }}"
    vm_size: "{{ lookup('env', 'VM_SIZE') }}"
    resource_group: corelibraries-ci-rg
  tasks:

  - name: Update scale set
    azure_rm_virtualmachinescaleset:
      resource_group: "{{ resource_group }}"
      name: "{{ vmss_name }}"
      ssh_password_enabled: true
      capacity: 1
      upgrade_policy: Manual
      tier: Standard
      overprovision: false
      single_placement_group: false
      vm_size: "{{ vm_size }}"
      virtual_network_name: corelibs-linux-agentsVNET
      subnet_name: corelibs-linux-agentsSubnet
      image:
        name: "{{ image_name }}"
        resource_group: "{{ resource_group }}"

  - name: List all of the instances
    azure_rm_virtualmachinescalesetinstance_facts:
      resource_group: "{{ resource_group }}"
      vmss_name: "{{ vmss_name }}"
    register: instances

  - debug:
      var: instances

  - name: manually upgrade all the instances 
    azure_rm_virtualmachinescalesetinstance:
      resource_group: "{{ resource_group }}"
      vmss_name: "{{ vmss_name }}"
      instance_id: "{{ item.instance_id }}"
      latest_model: yes
    with_items: "{{ instances.instances }}"

```

##### EXPECTED RESULTS

The scale set is successfully updates

##### ACTUAL RESULTS

The above error is recieved. See attached text

https://paste.ubuntu.com/p/QGPpQDpjNS/

**Comment by planetmarshall** [comment]
Syntax error in playbook!

**Comment by planetmarshall** [comment]
Fixed the syntax error, issue remains.

**Comment by planetmarshall** [comment]
Resolved - had omitted to call
```
  ansible-galaxy collection install azure.azcollection
```

**Comment by planetmarshall** [comment]
Repoening as I am still seeing this after following the installation instructions for the requisite azure modules.

**Comment by planetmarshall** [comment]
Possibly related to #197 ?

**Comment by Fred-sun** [comment]
@planetmarshall Fixed by #197, will close. Thank you very much!

**Comment by planetmarshall** [comment]
I am still seeing this issue in 1.8.0. Steps to reproduce as above.
